import Head from "next/head";
import React from "react";
import Header from "../../components/header";

export default function Home(): React.ReactElement {
  return (
    <>
      <Head>
        <title>Table</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <main></main>
      <footer></footer>
    </>
  );
}
